server:
  port: 9008
spring:
  application:
    name: linguochao-rabbitmq #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.66.133:3306/tensquare_rabbitmq?characterEncoding=UTF8
    username: root
    password: root
  jpa:
    database: MySQL
    show-sql: true
  redis:
    host: 192.168.66.133
  rabbitmq:
    host: 192.168.66.133