server:
  port: 9010
spring:
  application:
    name: linguochao-feign #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.66.133:3306/linguochao_feign?characterEncoding=UTF8
    username: root
    password: root
  jpa:
    database: MySQL
    show-sql: true
jwt:
  config:
    key: itdan
    ttl: 1800000
eureka:
  client:
    service-url:   # 暴露Eureka的注册地址
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true   # 这个配置在本地可以是false，意味着使用localhost进行调用，但是远程独立部署的时候，这个配置就必须是true
feign:
  hystrix:
    enabled: true