server:
  port: 9002
#wagger多环境配置,是否开启,生产环境关闭,开发测试环境开启
swagger2:
  enable: true
  #swagger自定义文档路径
  markdowns: classpath:mardow/*
  #开启Swagger的Basic认证功能,默认是false
  basic:
    enable: true
    ## Basic认证用户名
    username: linguochao
    ## Basic认证密码
    password: 123456