service:
  port: 9001
spring:
  application:
     name: linguochao-jpa
  datasource: # 数据源
    url: jdbc:mysql://localhost:3306/linguochao_jpa?characterEncoding=UTF8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa: # JPA框架配置
    show-sql: true  # 打印sql语法
    # generate-ddl: true # 自动建表
    database: mysql  # 数据库类型
  rabbitmq:
    host: 192.168.184.135
eureka:
  client:
    service-url:   # 暴露Eureka的注册地址
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true   # 这个配置在本地可以是false，意味着使用localhost进行调用，但是远程独立部署的时候，这个配置就必须是true
